version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      #- echo "Installing AWS CLI on server"
      #- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #- unzip awscliv2.zip
      #- sudo ./aws/install
      - which aws
      - aws --version
      #- aws ecr create-repository --repository-name java-maven-app --region ap-south-1
  pre_build:
    commands:
      - echo "Pre-build stage"
  build:
    commands:
      - echo "Building Java Application"
      - mvn package
      - echo "ECR Login Config"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ecr_login_pwd
      - REPOSITORY_URI=$ecr_repository_uri
      - COMMIT_HASH="commit hash"
      - IMAGE_TAG=$COMMIT_HASH
      
  post_build:
   commands:
     - echo "Running unit tests"
     - mvn test

     - echo "Running Jacoco for code coverage..."
     - mvn jacoco:report

     - echo "Running OWASP Software Composition Analysis..."
     #- mvn org.owasp:dependency-check-maven:check

     - echo "Build Docker image"
     #- docker build -t $ecr_repository_uri . 
     #- docker tag java-maven-app:latest java-maven-app:$IMAGE_TAG
     - docker build -t java-maven-app .
     - docker tag java-maven-app:latest public.ecr.aws/j1l7w1m3/java-maven-app:latest

     - echo "Pushing Docker Image to ECR"
     - docker push public.ecr.aws/j1l7w1m3/java-maven-app:latest
