version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      #- echo "Installing AWS CLI on server"
      #- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #- unzip awscliv2.zip
      #- sudo ./aws/install
      - which aws
      - aws --version
      - aws ecr create-repository --java-maven-app --region ap-south-1
  pre_build:
    commands:
      - echo "Pre-build stage"
  build:
    commands:
      - echo "Building Java Application"
      - mvn clean install -DskipTests=true
  post_build:
   commands:
     - echo "Running unit tests"
     - mvn test

     - echo "Running Jacoco for code coverage..."
     - mvn jacoco:report

     - echo "Running OWASP Software Composition Analysis..."
     - mvn org.owasp:dependency-check-maven:check
